### ISSUE TITLE
Parser Support for importData

### ISSUE THREAD

**Issue by skylevis** [cs2103aug2015-t09-2j/main#60]
hi Dat, this is for recognizing the "import" command.
Eg:
import "D:\Data\MySchedule\"

**Comment by quangdatv** [comment]
Should be ok now
Below is example of parsing "import" command (taken from TestParser.java):

        // import
        CommandDetail importCommand = Parser.parseCommand("import D:\blabla");
        assertEquals(CommandType.IMPORT, importCommand.getCommandType());
        assertEquals("D:\blabla", importCommand.getFilePath());
