### ISSUE TITLE
Parser support for EditTask addon

### ISSUE THREAD

**Issue by skylevis** [cs2103aug2015-t09-2j/main#61]
This is for editing of description and category. Also i think we should not allow editing of Task ID.
Eg: This is the sample code snippet that i have under editTask().
```java
case CommandProperties.TASK_DESCRIPTION :
    editedTask.setDescription(editOption.getOptionValue());
    break;
case CommandProperties.TASK_CATEGORY :
    editedTask.setCategory(editOption.getOptionValue());
    break;
```

**Comment by quangdatv** [comment]
https://github.com/cs2103aug2015-t09-2j/main/commit/b20576c9e5a5275d14167adce8fd9650b1acbb2b
